from enum import Enum

RESOURCE_PATH = "../resources"

RACE_HUMAN = 0

GENDER_MALE = 20
GENDER_FEMALE = 21

ANIMATION_IDLE_UP    = 100
ANIMATION_IDLE_RIGHT = 101
ANIMATION_IDLE_DOWN  = 102
ANIMATION_IDLE_LEFT  = 103
